// generated 2004/2/8 21:52:22 CET by newmark@molly.(none)
// using glademm V2.0.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/newmark/devel/CyberDeck/thegame/interface/cyberdeck.glade
// for gtk 2.2.4 and gtkmm 2.2.7
//
// Please modify the corresponding derived classes in ./src/main.hh and./src/main.cc

#ifndef _MAIN_GLADE_HH
#  define _MAIN_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>

class main_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        
        main_glade();
        
        ~main_glade();
private:
        virtual void on_new1_activate() = 0;
        virtual void on_open1_activate() = 0;
        virtual void on_save1_activate() = 0;
        virtual void on_save_as1_activate() = 0;
        virtual void on_quit1_activate() = 0;
        virtual void on_cut1_activate() = 0;
        virtual void on_copy1_activate() = 0;
        virtual void on_paste1_activate() = 0;
        virtual void on_delete1_activate() = 0;
        virtual void on_about1_activate() = 0;
};
#endif
